# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:
  build:

    defaults:
      run:
        working-directory: src
  
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu (現行/過去 & netstandard)
          - os: windows-latest
            framework: netstandard2.0
            sdk: 8.0.x
          - os: ubuntu-latest
            framework: netstandard2.1
            sdk: 8.0.x
          - os: ubuntu-latest
            framework: netcoreapp3.1
            sdk: 3.1.x
          - os: ubuntu-latest
            framework: net5.0
            sdk: 5.0.x
          - os: ubuntu-latest
            framework: net6.0
            sdk: 6.0.x
          - os: ubuntu-latest
            framework: net7.0
            sdk: 7.0.x
          - os: ubuntu-latest
            framework: net8.0
            sdk: 8.0.x
          - os: ubuntu-latest
            framework: net9.0
            sdk: 9.0.x
          # Windows ONLY for net462
          - os: windows-latest
            framework: net462
            sdk: 8.0.x

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        # net462 も SDK スタイルなら dotnet SDK 必要。Visual Studio の targeting pack が runner に入っている。
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.sdk }}
          # net9.0 が Preview の場合:
          # include-prerelease: true

      - name: Display SDK info
        run: dotnet --info

      - name: Restore
        run: dotnet restore

      - name: Build (single target)
        run: dotnet build ZstdSharp/ZstdSharp.csproj -c Release -f ${{ matrix.framework }} --no-restore
      - name: Build (legacy)
        if: ${{ contains(fromJson('["netcoreapp3.1","net5.0","netstandard2.0","net462"]'), matrix.framework) }}
        run: dotnet build Zstd.Extern/Zstd.Extern.csproj -c Release -f ${{ matrix.framework }} --no-restore
      - name: Build (runtime)
        if: ${{ !contains(fromJson('["netstandard2.0","netstandard2.1"]'), matrix.framework) }}
        run: |
         dotnet build Sandbox/Sandbox.csproj -c Release -f ${{ matrix.framework }} --no-restore
         dotnet build ZstdSharp.Test/ZstdSharp.Test.csproj -c Release -f ${{ matrix.framework }} --no-restore
         dotnet build ZstdSharp.Benchmark/ZstdSharp.Benchmark.csproj -c Release -f ${{ matrix.framework }} --no-restore

      - name: Test (single target)
        # net462 のテストプロジェクトが存在しない / 失敗する場合は条件分岐で Skip
        run: dotnet test -c Release -f ${{ matrix.framework }} --no-build --verbosity normal
